
export const errors_message = {
    "USER_PASSWORD_UPDATED": "The Password Updated Successfully",
    "REMOVE_FROM_PLAYLIST": "Removed from playlist successfully",
    "REMOVE_DATA": "Data removed successfully",
    "FAILED_TO_REMOVE": "Failed to remove data",
    "ADDED_TO_PLAYLIST": "Added to playlist successfully",
    "MOBILE_NUMBER_NOT_AVAILABLE": "Mobile login is not available in current country",
    "NO_STREAM":"No Stream Available",
    "AVAILABILITY":"AvailabilityList Missing",
    "ADDED":"Added Successfully",
    "CREATED":"Created Playlist Successfully..!",
    "TICKET":"Ticket Created Successfully",
    "PROFILE_UPDATED":"Profile Updated Successfully",
    "ENTER_6_DIGIT_OTP": "Please Enter 6 digit OTP",
    "OTP_SHOULD_NOT_EMPTY": "OTP should be not empty!",
    "NAME_SHOULD_MIN_THREE_CHAR": "Name should be minimum 3 character",
    "NAME_SHOULD_NOT_EMPTY": "Name should be not empty!",
    "PROFILE_CRETE_SUCCESSFULLY": "Profile Create Successfully",
    "OPT_SHOULD_BE_6_DIGIT":"OTP should be 6 digit",
    "OTP_REQUIRED":"OTP required",
    "NEW_PASSWORD_SHOULD_BE_MINIMUM_SIX_AND_MAXIMUM_FIFTEEN_CHARACTERS":"New Password should be minimum 6 and maximum 15 characters",
    "ENTER_NEW_PASSWORD":"Enter new password!",
    "PLEASE_ENTER_VALID_OTP":"Please Enter Valid OTP",
    "MESSAGE_SHOULD_BE_MINIMUM_TEN_AND_MAXIMUM_TWOFIFTYSIX_CHARACTERS":"Message should be minimum 10 and maximum 256 characters",
    "MESSAGE_SHOULDNT_BE_EMPTY":"Message shouldn't be empty!",
    "TITLE_SHOULD_BE_MINIMUM_FIVE_AND_MAXIMUM_HUNDRED_CHARACTERS":"Title should be minimum 5 and maximum 100 characters",
    "PASSWORD_SHOULD_BE_MAXIMUM_16_CHARACTERS":"Password should be maximum 16 characters",
    "PASSWORD_SHOULD_BE_MINIMUM_6_CHARACTERS":"Password should be minimum 6 characters",
    "PASSWORD_REQUIRED":"Password Required!",
    "EMAIL_OR_MOBILE_NUMBER_REQUIRED":"Email or mobile number required!",
    "PLEASE_ENTER_A_VALID_MOBILE_NUMBER":"Please enter a valid mobile number",
    "MOBILE_NUMBER_REQUIRED":"Mobile number required",
    "PLEASE_FILL_OUT_THIS_FIELD":"Please fill out this field",
    "THE_COUNTRY_CODE_COULD_NOT_BE_FETCHED_PLEASE_TRY_AGAIN_AFTER_SOMETIME":"The Country code could not be fetched! Please try again after sometime",
    "PLEASE_ENTER_A_VALID_EMAIL_ADDRESS":"Please enter a valid email address",
    "NAME_SHOULD_HAVE_MINIMUM_2_AND_MAXIMUM_32_CHARACTERS":"Name should have minimum 2 and maximum 32 characters",
    "NAME_REQUIRED":"Name Required",
    "OTP_HAS_BEEN_SENT_TO_YOUR_MOBILE_NUMBER":"OTP has been sent to your mobile number",
    "SOMETHING_WENT_WRONG_PLEASE_TRY_AFTER_SOMETIME":"Something wrong please try after sometime",
    "YOUR_PROFILE_PIN_IS_DISABLED":"Your profile pin is disabled",
    "AVAILABILITY_NOT_LOADED":"Availability not loaded",
    "NO_DATA_FOUND":"No Data Found",
    "UNKNOWN_ERROR":"Unknown error",
    "OTP_SENT_ON_REGISTERED_EMAIL_MOBILE":"OTP sent on registered email/mobile",
    "PLEASE_ENTER_VALID_PIN":"Please enter valid pin",
    "NO_STATUS_UPDATE":"No status update"
}